// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reception.Infrastructure.Persistence;

#nullable disable

namespace Reception.Infrastructure.Migrations
{
    [DbContext(typeof(ReceptionDbContext))]
    partial class ReceptionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reception.Domain.Models.Carton", b =>
                {
                    b.Property<string>("CartonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PaletteId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CartonId");

                    b.HasIndex("PaletteId");

                    b.ToTable("Cartons");
                });

            modelBuilder.Entity("Reception.Domain.Models.Command", b =>
                {
                    b.Property<string>("CommandId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CommandId");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("Reception.Domain.Models.Palette", b =>
                {
                    b.Property<string>("PaletteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CommandId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PaletteId");

                    b.HasIndex("CommandId");

                    b.ToTable("Palettes");
                });

            modelBuilder.Entity("Reception.Domain.Models.Product", b =>
                {
                    b.Property<string>("RefId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CartonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefId");

                    b.HasIndex("CartonId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Reception.Domain.Models.Carton", b =>
                {
                    b.HasOne("Reception.Domain.Models.Palette", "Palette")
                        .WithMany("Cartons")
                        .HasForeignKey("PaletteId");

                    b.Navigation("Palette");
                });

            modelBuilder.Entity("Reception.Domain.Models.Palette", b =>
                {
                    b.HasOne("Reception.Domain.Models.Command", "Command")
                        .WithMany("Palettes")
                        .HasForeignKey("CommandId");

                    b.Navigation("Command");
                });

            modelBuilder.Entity("Reception.Domain.Models.Product", b =>
                {
                    b.HasOne("Reception.Domain.Models.Carton", "Carton")
                        .WithMany("Products")
                        .HasForeignKey("CartonId");

                    b.Navigation("Carton");
                });

            modelBuilder.Entity("Reception.Domain.Models.Carton", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Reception.Domain.Models.Command", b =>
                {
                    b.Navigation("Palettes");
                });

            modelBuilder.Entity("Reception.Domain.Models.Palette", b =>
                {
                    b.Navigation("Cartons");
                });
#pragma warning restore 612, 618
        }
    }
}
